// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"my_project/backend/internal/app"
	"my_project/backend/internal/auth"
	"my_project/backend/internal/config"
	"my_project/backend/internal/couples"
	"my_project/backend/internal/dates"
	"my_project/backend/internal/httpserver"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config) (*app.App, error) {
	logger := app.NewLogger(cfg)
	service := auth.NewService()
	couplesService := couples.NewService()
	datesService := dates.NewService()
	server := httpserver.New(logger, cfg, service, couplesService, datesService)
	appApp := app.New(server, logger)
	return appApp, nil
}
